Add first-timer info page
FreeCodeCampOKC/fccokc_web_legacy pull request #123
Opened 2017-10-25 19:45 UTC by chris-tse

## Related Issue

Resolves #122 

### Description

Adds page as described in the issue

### Checklist

- [x] I have read and understand the <a href='https://github.com/FreeCodeCampOKC/fccokc_web/blob/master/CODE_OF_CONDUCT.md'>CODE OF CONDUCT</a> as outlined
- [x] I have read the <a href='https://github.com/FreeCodeCampOKC/fccokc_web/blob/master/CONTRIBUTING.md'>CONTRIBUTING</a> document
- [x] My repository is up to date, and merge conflicts have been resolved
- [x] This pull request relates to an open issue and has been tagged above

### Who needs to review this change?

2017-10-25 20:02 UTC, mattstub requested changes
@chris-tse love the page for the most part, I would run the majority of the wording through hemingway just to make it a little more approachable. Great stuff!

2017-10-25 20:02 UTC, mattstub commented on docs/firsttimers.html
> +                        <li><a href="#">Resources</a></li>
could you update this link on the mobile nav bar?

2017-10-25 20:02 UTC, mattstub commented on docs/firsttimers.html
> +                        <p>There are no required materials to attend a FreeCodeCamp meetup. You may want to bring some pen and paper to take notes during talks. Many of our members also bring their l
This wording seems a bit rough, maybe pass it through [hemingway](http://www.hemingwayapp.com/) and clean it up some? Also I believe it would be 'bring a pen and paper' ?

2017-10-31 14:30 UTC, kacollins commented on docs/firsttimers.html
> +                        <li><a href="#">Resources</a></li>
This will be addressed in issue #128.

2017-10-31 14:30 UTC, kacollins commented on docs/firsttimers.html
> +                        <p>There are no required materials to attend a FreeCodeCamp meetup. You may want to bring some pen and paper to take notes during talks. Many of our members also bring their l
This will be addressed in issue #128.

2017-10-31 14:34 UTC, merged

2017-10-31 14:35 UTC, kacollins commented
Great job on this, @chris-tse! I think it will be really helpful for new attendees.