Added my information to the contributors section to the about.html
FreeCodeCampOKC/fccokc_web_legacy pull request #15
Opened 2017-08-09 02:21 UTC by stu7

2017-08-09 03:12 UTC, CarsonMcKinstry commented on docs/about.html
> +                        <li><a href="https://github.com/stu7" target="blank" title="Norman Haase" rel="external">Norman Haase</a></li>
target attribute in your `<a>` won't open a new tab/window.

2017-08-09 03:15 UTC, CarsonMcKinstry submitted a review, later dismissed
Good starting point!
You might take a look at some of the issues in this repo, see if it is something you can do, and then let me know when this PR is ready.

2017-08-10 05:02 UTC, stu7 commented
Are you looking for fixes from issues added to this initial PR?

2017-08-10 16:20 UTC, stu7 commented
Initial attribute fix to <a> was made in initial PR.

2017-08-23 04:24 UTC, stu7 commented
I'll continue to work through on practice issues here, correct any errors and push them back out

2017-08-29 05:48 UTC, stu7 commented on docs/about.html
> +                        <li><a href="https://github.com/stu7" target="blank" title="Norman Haase" rel="external">Norman Haase</a></li>
Fixed this error

2017-08-29 06:12 UTC, stu7 commented
Additions changes were made to the index.html and projects.html in this initial PR. PR is ready for review.

2017-09-21 19:20 UTC, dashcraft requested changes
There is an opened ul tag by the Techlahoma reference. Can you please close it or remove it, if it is unnecessary.

2017-10-02 02:28 UTC, mstub commented
working on cleaning this up in a new PR

2017-10-02 02:28 UTC, closed without merging