Update about.html for issue #20
FreeCodeCampOKC/fccokc_web_legacy pull request #29
Opened 2017-08-12 03:06 UTC by MasonT3

Add link to freecodecamp.org and remove references to Node and Angular.

2017-08-12 20:07 UTC, CarsonMcKinstry reviewed
Once you've got the link fixed, I'll merge this!

2017-08-12 20:07 UTC, CarsonMcKinstry commented on docs/about.html
> +                    <p>Free Code Camp Oklahoma City is the Oklahoma City branch of <a href="https://www.freecodecamp.org/" target="_blank" title="freeCodeCamp" rel="external">freecodecamp</a>. <br><b
Make sure capitalize Free Code Camp

2017-08-12 23:35 UTC, MasonT3 commented
Capitalized the website url.

2017-08-13 19:48 UTC, CarsonMcKinstry requested changes

2017-08-13 19:48 UTC, CarsonMcKinstry commented on docs/about.html
> +    <meta property="og:description" content="Free Code Camp - OKC is a group for those who want to learn to code in the Oklahoma City area.  We meet at StarSpace46 every Sunday."
Forgot a closing bracket on the meta tag

2017-08-13 19:48 UTC, CarsonMcKinstry commented on docs/about.html
> +                    <p>Free Code Camp Oklahoma City is the Oklahoma City branch of <a href="https://www.FreeCodeCamp.org/" target="_blank" title="FreeCodeCamp" rel="external">freecodecamp</a>. <br><b
I meant the text inside of the anchor tag

2017-08-13 20:27 UTC, MasonT3 commented
Sorry, I got confused. I fixed it now.

2017-08-14 18:20 UTC, CarsonMcKinstry commented
@MasonT3 Make sure to fix the other issue in `docs/about.html`. It looks like you're still missing a closing bracket on line 12.

2017-08-16 17:58 UTC, MasonT3 commented
Committed the closing bracket. Sorry this has been taking long. First time trying to figure out and contribute to open source

2017-08-17 14:55 UTC, CarsonMcKinstry approved these changes

2017-08-17 14:57 UTC, CarsonMcKinstry commented
@MasonT3 Not a problem! One tip is that when you get a change request, go through each change and make sure they're at least updated before pushing again.

2017-08-17 14:57 UTC, merged

2017-08-17 15:23 UTC, MasonT3 commented
Thanks for the tip!