Fix mobile nav on slack page
FreeCodeCampOKC/fccokc_web_legacy pull request #65
Opened 2017-10-01 23:56 UTC by brycejech

Closes #62.
Updated the fa icon to use the hamburger icon.
Also updated the blog-title heading to point to index.html to behave like the rest of the site.

2017-10-02 01:29 UTC, Jason9199 requested changes
While you did correct the hamburger icon, and you also correctly caught that the link for the h1 Free Code Camp was not correct based on the way things are done on the other pages (good catch!), the icon won't do anything as it is now. Look at the other pages and see how the mobile nav bar is implemented. In the code it'll look like there's actually two nav bars, and there are. But one is used for normal size pages while the other is used for mobile sized pages. Look for that and please add that to this page to confirm that when the hamburger icon is clicked the nav bar opens and then when it's clicked again the nav bar closes. I'd recommend a tool like https://www.npmjs.com/package/http-server (something I use) to fire up the site locally and test your changes before submitting a pull request to increase your chances of it being accepted and merged in. Please let me know if you have any questions about running it locally.

2017-10-02 13:09 UTC, brycejech commented
@Jason9199, should be fixed now. Thanks for pointing that out ;)
I fixed it and pushed the changes to my branch. Is that it or is there something else I'll need to do to get the change merged in?
Thanks!

2017-10-02 14:14 UTC, Jason9199 commented
@brycejech Nope, just pushing your changes to that branch is enough. At first glance to the code it looks good. I'll pull down that change and test it this evening to be 100% sure.

2017-10-03 01:28 UTC, Jason9199 approved these changes

2017-10-03 01:28 UTC, merged