Added a link and description to projects about the fccokc github repo…
FreeCodeCampOKC/fccokc_web_legacy pull request #75
Opened 2017-10-03 20:04 UTC by stu7

…sitory

2017-10-04 14:05 UTC, mattstub requested changes
@stu7 I would propose that we remove the original wording about the website cloned, and also the new comments seem a little lengthy, perhaps we can remove the line about contacting Kimberly & Carson as the CONTRIBUTING file should help steer people that way.

(edit: for spelling mistakes)

2017-10-09 02:09 UTC, mstub commented
@stu7 how are these revisions coming? Everything working out okay?

2017-10-10 12:48 UTC, stu7 commented
@mstub Was out of town part of last week and busy this weekend. Will look at it soon and make the mods.

2017-10-10 13:42 UTC, mstub commented
@stu7 great! just wanted to make sure nothing was hanging you up to bad

2017-10-14 03:10 UTC, stu7 commented
@mstub Good week for work, bad week for coding. More of the same for Mon/Tues, out of state. We'll see how much I can get done to finally finish this one up.

2017-10-21 12:05 UTC, mattstub requested changes
Please note the 1 change about line 85. Everything else looks good. Thanks!

2017-10-21 12:05 UTC, mstub commented on docs/projects.html
> +                    <h3 id="FCC Github">FCC OKC Github</h3><p class ="github repo">Free Code Camp OKC welcomes aspiring developers to become contributors to the OKC website. There are a number of iss
Could you move line 85 down to the bottom of the page? Under the twitch bot project? In its current place it feels like the page is broken into two sections.. thanks @stu7

2017-10-25 20:11 UTC, mattstub approved these changes

2017-10-25 20:11 UTC, merged